/**
 * Created by mengwliu on 9/7/16.
 * 389. Find the Difference
 *  Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 */
public class p389 {
    public char findTheDifference(String s, String t) {
        int[] memo = new int['z'-'a'+1];
        for (char c:s.toCharArray()) {
            memo[c-'a'] ++;
        }
        for (char c:t.toCharArray()) {
            memo[c-'a']--;
            if (memo[c-'a'] == -1) return c;
        }
        return 'a';
    }
}
